### ISSUE TITLE
dll fail sklearn

### ISSUE THREAD

**Issue by suraj156** [suraj156/suraj156#1]

**Comment by suraj156** [comment]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Aakash\Desktop\python>python -u "c:\Users\Aakash\Desktop\python\main2.py"
Traceback (most recent call last):
  File "c:\Users\Aakash\Desktop\python\main2.py", line 1, in <module>
    import sklearn
  File "C:\Users\Aakash\AppData\Local\Programs\Python\Python37-32\lib\site-packages\sklearn\__init__.py", line 76, in <module>
    from .base import clone
  File "C:\Users\Aakash\AppData\Local\Programs\Python\Python37-32\lib\site-packages\sklearn\base.py", line 16, in <module>
    from .utils import _IS_32BIT
  File "C:\Users\Aakash\AppData\Local\Programs\Python\Python37-32\lib\site-packages\sklearn\utils\__init__.py", line 14, in <module>
    from scipy.sparse import issparse
  File "C:\Users\Aakash\AppData\Local\Programs\Python\Python37-32\lib\site-packages\scipy\sparse\__init__.py", line
230, in <module>
    from .csr import *
  File "C:\Users\Aakash\AppData\Local\Programs\Python\Python37-32\lib\site-packages\scipy\sparse\csr.py", line 13, in <module>
    from ._sparsetools import (csr_tocsc, csr_tobsr, csr_count_blocks,
ImportError: DLL load failed: The specified module could not be found.




please help. please give solution of this problem,
